### PR TITLE
fix ERROR: unknown expr type *ast.IndexListExpr

### PR DESCRIPTION
**Pull request by ilius**
Fix `ERROR: unknown expr type *ast.IndexListExpr`
With a test.

### CODE REVIEW

**Comment by alexkohler** [comment]
Thank you!

**Comment by ilius** [comment]
No worries.

Are you going to do `go mod init`?

Generics were added in Go 1.18.

But even if I change to go 1.17 in `go.mod`, `go test` still works!
Not sure why!

**Comment by ilius** [comment]
https://github.com/golang/go/commit/0406d3a8e5301bd5fd697018e6e8fbb9c75eeb42

**Comment by ilius** [comment]
`MultiIndexExpr` was renamed to `IndexListExpr` in [go1.18beta1](https://github.com/golang/go/releases/tag/go1.18beta1)

https://github.com/golang/go/commit/0406d3a8e5301bd5fd697018e6e8fbb9c75eeb42

**Comment by alexkohler** [comment]
Ah. Opened a PR here: https://github.com/alexkohler/nargs/pull/5 - I'm admittedly not super familiar with Go modules :sweat_smile: Any thoughts on what version to specify?

**Comment by ilius** [comment]
Go 1.18 or above should be fine.

**Pull request merged**
